on:
  push:
    branches:
      - master

name: release-please

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: |
            pages deploy dist --project-name=schasteband-web
